### ISSUE TITLE
Add a full rules list for linting

### ISSUE THREAD

**Issue by jamescallumyoung** [joshghent/gifbar#102]
The "code quality" check for Pull Requests (done by Codacy) is trying to enforce some linting rules but there's no linting rules in the repo.

I added a basic .eslintrc in #101 but we should decide on a full linting rule list.

I would suggest we use ESLint, with either the "semistandard" or "AirBnb" rules.

**Comment by dhuang612** [comment]
I would like to work on this

**Comment by dhuang612** [comment]
created PR #105

**Comment by dhuang612** [comment]
made requested changes

**Comment by dhuang612** [comment]
switched travis config file to run yarn instead of npm

**Comment by joshghent** [comment]
Completed in #105 - thank you @dhuang612

**Comment by jamescallumyoung** [comment]
Thanks for tackling this @dhuang612! 🎉
