### ISSUE TITLE
Add support for other gif apis

### ISSUE THREAD

**Issue by joshghent** [joshghent/gifbar#11]
Add support for other api's such as tenor

**Comment by QuadDepo** [comment]
Could you list a few services that you might would like to add?

Would this work together with others where you can check a list on or off?

**Comment by joshghent** [comment]
Hi @QuadDepo - thanks for taking an interest in this.
The only API's I can find that do GIF's are
Tenor - https://tenor.com/gifapi/documentation
OpenGifAPI - https://github.com/bryanstedman/open-gif-api - still a WIP but looks cool

Tenor will probably be the easiest to implement 👍 Maybe if we find any more we can create new issues for them. Let's keep this issue just for adding tenor. Is this something you'd be interested in working on?

**Comment by jamescallumyoung** [comment]
Hey @joshghent, if @QuadDepo isn't interested, I'd like to pick this up.

I don't really want to touch the UI but I can abstract away the giphy dependency, add tenor, and make it easier to add other APIs in the future.

**Comment by joshghent** [comment]
@jamescallumyoung That sounds like a great idea! Thanks a lot, would be amazing if you could pick this up 👍 If you need any help, let me know 🎉 
P.S. Make sure to sign up for Hacktoberfest, because if you submit 4 PR's you can win some prizes! 👻

**Comment by jamescallumyoung** [comment]
> That sounds like a great idea! Thanks a lot, would be amazing if you could pick this up 👍 If you need any help, let me know 🎉

Cheers @joshghent!

---

I took a look earlier but starting the app failed for me, is there something I'm missing?

I ran `$ yarn start` and got the application in my tray, but the window it renders is always empty (plain white). 

The dev tools gave me the "cannot load local resource: <path/to/repo/dist/main.html>" message.

Any help getting off the ground would be appreciated :) 

---

> P.S. Make sure to sign up for Hacktoberfest, because if you submit 4 PR's you can win some prizes! 👻

Hmm. Didn't know about this. Pretty cool stuff 😄 Could you add the "hacktoberfest" label?

**Comment by joshghent** [comment]
Huh that is weird @jamescallumyoung - what platform are you on?

**Comment by jamescallumyoung** [comment]
Platform details:

MacOS     (Mojave) 10.14.6
Node        10.16.3
NPM         6.9.0
Yarn          1.19.1
electron    4.0.0
react         16.8.3

---

Looks like an issue with electron picking up main.js as the entry point.

If I add an index.html to the dist dir (manually) that renders fine.

To help:
- Am I missing something react-y? Not used to reactXelectron dev.
- Could you post a full list of commands you use to get it up and running. 
- Do you have any globally installed dependencies that are not in the package.json?

Thanks for the help here. I have the API changes working 😀 but I can't render them results to check it in-app 😢

**Comment by joshghent** [comment]
Hmm that's very weird, I cannot see any dependencies that I have globally...
I just run `yarn watch` and then open up the build package 🤷‍♂ - nothing special
Maybe it has stopped working because of a new version of yarn?

I think someone is working on this issue in #100 - I'm happy for you to make your PR and we can test it later 👍 Maybe we can see if the yarn.lock file has changed which may have caused issues. Thank you so much for your work on this! Great work 👍

**Comment by jamescallumyoung** [comment]
N.B. I found: [The Imgur API docs](https://apidocs.imgur.com/?version=latest#3c981acf-47aa-488f-b068-269f65aee3ce) and they have a filter for just Gifs. We could integrate that too.

**Comment by jamescallumyoung** [comment]
I decided that since the support for other APIs is going to get pretty big, and since the code is really reusable, I moved it to an external module. It's on npmjs.com here: [@jych/gif-provider](https://www.npmjs.com/package/@jych/gif-provider).

I'll make a PR for the integration here later today.

**Comment by jamescallumyoung** [comment]
#106 adds support for the Tenor API. Since this issue is just for adding Tenor support, I'll consider it complete if #106 gets approved.

I suggest we consider how we want to enable/disable each API in a separate feature request.

**Comment by joshghent** [comment]
Wow that's amazing! Nice work dude!
I think we'd have to create a little UI that allows the user to enable or disable it. Alternatively, we could just create a config file somewhere and then people can change it themselves for the time being 👍

**Comment by joshghent** [comment]
Gonna mark this as done 👍
