### ISSUE TITLE
There's currently a build error

### ISSUE THREAD

**Issue by dhuang612** [joshghent/gifbar#111]
Hi,

I noticed that the build is currently failing.
Here are the logs related to that:
https://travis-ci.org/joshghent/gifbar/jobs/601497068

It seems to have been failing since my push
```
/home/travis/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
```

**Comment by larryschirmer** [comment]
@dhuang612 I was having the same error building the project this afternoon. I was able to resolve the issue by downgrading node to 11.15.0
