### ISSUE TITLE
Convert to using yarn

### ISSUE THREAD

**Issue by joshghent** [joshghent/gifbar#16]
We have a mix of npm and yarn scripts, let's stick to just yarn

**Comment by Fabianopb** [comment]
As this is an action of https://github.com/joshghent/gifbar/issues/7 I can also take it! :)

**Comment by Fabianopb** [comment]
PR submitted: https://github.com/joshghent/gifbar/pull/18

**Comment by joshghent** [comment]
Thanks again @Fabianopb for completing this 👍
