### ISSUE TITLE
Replace badges in README

### ISSUE THREAD

**Issue by jamescallumyoung** [joshghent/gifbar#161]
The README currently shows badges for greenkeeper and TravisCI at the top. These badges are no longer useful because greenkeeper has been shut down and this project no longer uses TravisCI.

We would liek to:
- remove both of the current badges
- add a badge for the current dependency status from Snyk
- add a badge for the current test status from Codacy

Suggestions for additional badges are welcome!

**Comment by sanskar-p** [comment]
Hi @jamescallumyoung 
Please verify if these are the right badges -
[![Known Vulnerabilities](https://snyk.io/test/github/joshghent/gifbar/badge.svg)](https://snyk.io/test/github/joshghent/gifbar)
[![Codacy Badge](https://api.codacy.com/project/badge/Grade/6070b197c3644c03bb3f0ec79d641675)](https://app.codacy.com/app/joshghent/gifbar?utm_source=github.com&utm_medium=referral&utm_content=joshgrent/gifbar&utm_campaign=Badge_Grade_Settings)

If yes, I will create a PR for the necessary changes.

**Comment by jamescallumyoung** [comment]
Thanks for taking a look at this so soon @sanskar-p! 🚀

Those look good to me but I suspect @joshghent would know for sure as he set up Snyk and Codacy. If you could open a PR with the changes and add him to the reviewers, that would be perfect!

**Comment by sanskar-p** [comment]
@jamescallumyoung I've opened a PR but I'm unable to add @joshghent as a reviewer.

**Comment by joshghent** [comment]
Thank you to @sanskar-p for resolving this! Great work! Resolved in #162
