### ISSUE TITLE
Rename react files to use JSX extension

### ISSUE THREAD

**Issue by jamescallumyoung** [joshghent/gifbar#170]
Currently, the React files have the JS extension, not JSX. Example: `gifBar.js` should be `gifbar.jsx`. The node scripts may need to be updated to include the `.jsx` extension in some cases.

This was fixed in #169 but was reverted as it caused github to not be able to create a clean git diff.

**Comment by felix-chin** [comment]
@jamescallumyoung I'll work on this issue, please assign. Thanks
