### ISSUE TITLE
Put build process into CI pipeline

### ISSUE THREAD

**Issue by joshghent** [joshghent/gifbar#22]
~Have the app build using Travis when pushing to the master branch. Make these downloads available somewhere.~

[Issue description updated at 2020-09-22]

Have successful merges to the `master` branch trigger a new release to be built. This could be done using either a dedicated build CI pipeline, the existing tools (codacy), or GitHub actions.

New builds should be saved as _Releases_ in GitHub. Tagging releases can be left as a manual jobfor now as that may effect #3 .

**Comment by willany** [comment]
Hi, I think you should enter on Travis CI site and allow your project on github:
<img width="834" alt="captura de tela 2018-10-29 as 10 43 50" src="https://user-images.githubusercontent.com/629029/47653549-96a04380-db67-11e8-90ab-9fa56bd794d9.png">

**Comment by willany** [comment]
Done

**Comment by joshghent** [comment]
@willany The travis file currently just runs the test suite.
We need to configure it to run the tests, then package it with electron-builder (for Windows, Mac and Linux), then if we are testing on the master branch then we should tag a new release and commit that along with all the built files. If we are on the develop branch then we should not do these steps

**Comment by jamescallumyoung** [comment]
This Issue is _old_! It looks like thr project is no longer using Travis for testing and is instead using Codacy and Snyk for CI.

Given that GitHub actions are now available, it may be worth looking into using them for the release process. What do you think @joshghent ?

I'll go ahead and update the Issue to reflect the new CI environment.

**Comment by joshghent** [comment]
@jamescallumyoung Yeah definitely want to move this over to Github Actions for CI. Codacy and Synk are just tools for checking code quality and security. GH Actions needs to be used for the deployment etc.
Is this an issue you could tackle?

**Comment by jamescallumyoung** [comment]
Yeah, I can take a look at this. I'm likely to look into #74 first though as I'm not sure how brew handles releases and if that will have any impact on setting up the CI.

If I don't get time, I'll add a label or two and unassign myself, so someone else can take a look.
