### ISSUE TITLE
Implement Jest automated tests

### ISSUE THREAD

**Issue by joshghent** [joshghent/gifbar#7]
Add the following tests using jest or something. Add to a travis CI process.

- Make sure we can still see the powered by giphy logo
- You can still search for gifs
- Clicking on a gif will copy it

**Comment by Fabianopb** [comment]
Hey @joshghent I could take a look at this one, I have experience with `jest`, `enzyme` and `travisCI`!

**Comment by joshghent** [comment]
@Fabianopb That would be fantastic! Thank you so much! I do not know much about frontend testing so I could learn a lot from this! 👍

**Comment by joshghent** [comment]
This will solve #12 too

**Comment by Fabianopb** [comment]
Awesome, I'll do it later today!

**Comment by Fabianopb** [comment]
Referencing the PR: https://github.com/joshghent/gifbar/pull/14
And this issue can be closed! :)
