### ISSUE TITLE
Package for linux

### ISSUE THREAD

**Issue by joshghent** [joshghent/gifbar#8]
Use https://github.com/unindented/electron-installer-debian to package for debian/ubuntu
Add a command in the package.json for building for linux

**Comment by maxzirps** [comment]
Hey, would like to start working on this

**Comment by joshghent** [comment]
@zirmax Hey! It's all yours my friend, thank you very much! Let me know if you need any help

**Comment by maxzirps** [comment]
@joshghent I implemented the linux-build-process, but the app is not working on linux. `yarn start` runs without error, but there is no icon in the tray.

Should I merge anyway, since the build process works and create a new issue for this?

**Comment by joshghent** [comment]
@zirmax Yeah sure thing dude, that sounds like a good plan. If you'd be able to investigate that would be amazing. I don't have a Linux box around at the moment so would appreciate your insights

**Comment by maxzirps** [comment]
> @zirmax Yeah sure thing dude, that sounds like a good plan. If you'd be able to investigate that would be amazing. I don't have a Linux box around at the moment so would appreciate your insights

Will do ;)
